### ISSUE TITLE
Infinite Scroll Demo Missing?

### ISSUE THREAD

**Issue by kawalsh** [desandro/masonry-docs#20] opened 2015-05-24 20:48 UTC
I followed a link from the masonry-rails gem github (https://github.com/kristianmandrup/masonry-rails), which implied that there should be an infinite scroll demo on this page (http://masonry.desandro.com/demos/infinite-scroll.html)

Not a big deal, just thought you should know.

**Comment by desandro** [comment] 2015-05-25 14:40
Thanks for reporting this issue. Closing as a duplicate of #1

**Closed by desandro** 2015-05-25 14:40 UTC

**Comment by guykatz** [comment] 2015-10-26 11:59
so is there an infinite scroll baked into masorny or not?
thanks!
